language: node_js
node_js:
  - '0.10.33'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma jshint'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages
after_script: "cat ./dist/reports/coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js"